[settings]
directory = "." # Current directory
units = "lj"

[md]
steps = 1000

[box]
periodic = [true, true, true]
low = [0.0, 0.0, 0.0]
high = [1.0, 1.0, 1.0]

[particles]
file = "initial.xyz"

[particles.velocity]
temperature = 1.0
momentum = true
seed = 1

[integrator]
class = "VelocityVerlet"
timestep = 0.005
