[settings]
directory = "." # Current directory

[md]
steps = 1000

[box]
periodic = [true, true, true]
low = [0.0, 0.0, 0.0]
high = [1.0, 1.0, 1.0]

[particles]
file = "initial.xyz"

[integrator]
class = "VelocityVerlet"
timestep = 0.005
