[settings]
directory = "." # Current directory

[md]
total_steps = 1000
temperature = 1.0

[box]
periodic = [true, true, true]
low = [0.0, 0.0, 0.0]
high = [1.0, 1.0, 1.0]

[particles]
file = "initial.xyz"
format = "xyz"

[integrator]
class = "VelocityVerlet"
timestep = 0.005
