name: Hello world workflow

on:
  push:
    branches:
      - main
      - add-actions
  pull_request:
    branches:
      - main
      - add-actions
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash


  lint:
    name: "Run linting"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2

      - name: "Define virtual environment for Poetry"
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: "Define a cache for the virtual environment based on the dependencies lock file"
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: "Install the project dependencies"
        run: poetry install
